name: Scrape de datos AFA 

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '20,50 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
      options: --mount type=bind,source=${{ github.workspace }},target=/github/workspace
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run scraper
      run: python get_text_file.py
    - name: Commit & push if changed
      run: |-
        cd /github/workspace
        date=$(date)
        git config --global --add safe.directory "/github/workspace"
        git config user.name "Automatic"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git commit -m "Cambios"|| exit 0
        git push
